# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a00f143a6f12045d7c137db6b97fd6115850271af4ff49ea9ae373d30bc1eb719401bdc4bbf333f871f3e20fd85a9ca04d045f8d6445c4b2e7338d62a65561f

test:
  secret_key_base: 9687baa888a825c20ffb1396293206bf26e3d89e56c15c5c20b60f3416c6dd02d6e78d83da17cc094613d830d4cdf465aa93d47d27c2644928f5e84636960785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
